In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("qoute_dataset.csv")

In [4]:
df

                                                  quote           Author
0     “The world as we have created it is a process ...  Albert Einstein
1     “It is our choices, Harry, that show what we t...     J.K. Rowling
2     “There are only two ways to live your life. On...  Albert Einstein
3     “The person, be it gentleman or lady, who has ...      Jane Austen
4     “Imperfection is beauty, madness is genius and...   Marilyn Monroe
...                                                 ...              ...
3033      The past beats inside me like a second heart.   John Banville,
3034  Damn, Claire. Warn a guy before you do a face-...    Rachel Caine,
3035  Can you be a girl for a few seconds?""I'm alwa...   Veronica Roth,
3036  That's what fiction is for. It's for getting a...      Tim O'Brien
3037  If we have no peace, it is because we have for...    Mother Teresa

[3038 rows x 2 columns]

In [5]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [6]:
quotes = quotes.str.lower()

In [7]:
import string
translator = str.maketrans('','', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [8]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

# **Tokenization**

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
vocab_size = 10000
tokeinizer = Tokenizer(num_words=vocab_size)
tokeinizer.fit_on_texts(quotes)

In [11]:
word_index = tokeinizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [12]:
sequence = tokeinizer.texts_to_sequences(quotes)

In [13]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [14]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [15]:
X = []
y = []

for seq in sequence:
  for i in range(1, len(seq)): # Changed from len(sequence) to len(seq)
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [16]:
len(X)

85271

In [17]:
len(y)

85271

In [18]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [20]:
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [21]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [22]:
y = np.array(y)

In [23]:
X_padded.shape

(85271, 745)

In [24]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [25]:
y_one_hot.shape

(85271, 10000)

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN ,LSTM, Dense

In [27]:
embedding_dim = 50
rnn_units = 128

In [28]:
rnn_model = Sequential()

rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [29]:
rnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [30]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
lstm_model = Sequential()

lstm_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [32]:
lstm_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [33]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
epochs = 10
batch_size = 128

In [35]:
rnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history_rnn = rnn_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 46s 70ms/step - accuracy: 0.0444 - loss: 6.7158 - val_accuracy: 0.0565 - val_loss: 6.5600
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.0764 - loss: 6.1298 - val_accuracy: 0.0848 - val_loss: 6.3346
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 0.0981 - loss: 5.7828 - val_accuracy: 0.1008 - val_loss: 6.3092
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 0.1139 - loss: 5.5037 - val_accuracy: 0.1033 - val_loss: 6.3163
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 0.1274 - loss: 5.2540 - val_accuracy: 0.1089 - val_loss: 6.3758
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.1388 - loss: 5.0233 - val_accuracy: 0.1110 - val_loss: 6.4556
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 0.1523 - loss: 4.8079 - val_accuracy: 0.1068 - val_loss: 6.4837
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 0.1687 - loss: 4.6039 - val_accuracy: 0.1101 - val_loss: 6.5450
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.1869 - loss: 4.4119 - val_accuracy: 0.1072 - val_loss: 6.6285
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.2092 - loss: 4.2291 - val_accuracy: 0.1055 - val_loss: 6.6834

In [36]:
epochs = 100
batch_size = 128

history_lstm = lstm_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 56ms/step - accuracy: 0.0386 - loss: 6.7596 - val_accuracy: 0.0473 - val_loss: 6.6804
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.0572 - loss: 6.3221 - val_accuracy: 0.0631 - val_loss: 6.5685
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0783 - loss: 6.0605 - val_accuracy: 0.0841 - val_loss: 6.4774
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.0960 - loss: 5.8418 - val_accuracy: 0.0936 - val_loss: 6.4567
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1063 - loss: 5.6683 - val_accuracy: 0.1021 - val_loss: 6.4390
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1177 - loss: 5.5032 - val_accuracy: 0.1080 - val_loss: 6.4357
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1265 - loss: 5.3473 - val_accuracy: 0.1081 - val_loss: 6.4606
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1343 - loss: 5.2033 - val_accuracy: 0.1098 - val_loss: 6.4915
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1402 - loss: 5.0683 - val_accuracy: 0.1103 - val_loss: 6.5311
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1471 - loss: 4.9381 - val_accuracy: 0.1112 - val_loss: 6.5851
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1540 - loss: 4.8138 - val_accuracy: 0.1116 - val_loss: 6.6284
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1601 - loss: 4.6923 - val_accuracy: 0.1140 - val_loss: 6.6828
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1679 - loss: 4.5724 - val_accuracy: 0.1140 - val_loss: 6.7467
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1768 - loss: 4.4552 - val_accuracy: 0.1129 - val_loss: 6.8095
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1857 - loss: 4.3406 - val_accuracy: 0.1106 - val_loss: 6.8667
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1976 - loss: 4.2282 - val_accuracy: 0.1110 - val_loss: 6.9455
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2107 - loss: 4.1212 - val_accuracy: 0.1132 - val_loss: 7.0248
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2242 - loss: 4.0174 - val_accuracy: 0.1129 - val_loss: 7.1079
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2381 - loss: 3.9207 - val_accuracy: 0.1130 - val_loss: 7.1873
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2522 - loss: 3.8288 - val_accuracy: 0.1114 - val_loss: 7.2684
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.2644 - loss: 3.7415 - val_accuracy: 0.1116 - val_loss: 7.3577
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2780 - loss: 3.6599 - val_accuracy: 0.1116 - val_loss: 7.4420
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.2882 - loss: 3.5838 - val_accuracy: 0.1109 - val_loss: 7.5038
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2996 - loss: 3.5112 - val_accuracy: 0.1103 - val_loss: 7.5855
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3109 - loss: 3.4426 - val_accuracy: 0.1085 - val_loss: 7.6665
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.3219 - loss: 3.3780 - val_accuracy: 0.1086 - val_loss: 7.7442
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.3326 - loss: 3.3151 - val_accuracy: 0.1051 - val_loss: 7.8233
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3415 - loss: 3.2539 - val_accuracy: 0.1069 - val_loss: 7.8864
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3514 - loss: 3.1960 - val_accuracy: 0.1041 - val_loss: 7.9547
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.3603 - loss: 3.1405 - val_accuracy: 0.1037 - val_loss: 8.0247
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.3693 - loss: 3.0866 - val_accuracy: 0.1040 - val_loss: 8.0865
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3781 - loss: 3.0343 - val_accuracy: 0.1041 - val_loss: 8.1637
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3866 - loss: 2.9822 - val_accuracy: 0.1018 - val_loss: 8.2383
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3956 - loss: 2.9324 - val_accuracy: 0.1031 - val_loss: 8.2966
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4049 - loss: 2.8848 - val_accuracy: 0.1011 - val_loss: 8.3603
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4123 - loss: 2.8377 - val_accuracy: 0.0996 - val_loss: 8.4291
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4202 - loss: 2.7921 - val_accuracy: 0.0978 - val_loss: 8.4881
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.4282 - loss: 2.7478 - val_accuracy: 0.0976 - val_loss: 8.5510
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4348 - loss: 2.7065 - val_accuracy: 0.0979 - val_loss: 8.6108
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4431 - loss: 2.6621 - val_accuracy: 0.0991 - val_loss: 8.6815
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4501 - loss: 2.6225 - val_accuracy: 0.0969 - val_loss: 8.7385
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4567 - loss: 2.5820 - val_accuracy: 0.0979 - val_loss: 8.7896
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4656 - loss: 2.5442 - val_accuracy: 0.0964 - val_loss: 8.8579
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4707 - loss: 2.5050 - val_accuracy: 0.0967 - val_loss: 8.9165
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.4770 - loss: 2.4682 - val_accuracy: 0.0955 - val_loss: 8.9832
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4843 - loss: 2.4319 - val_accuracy: 0.0955 - val_loss: 9.0383
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4909 - loss: 2.3976 - val_accuracy: 0.0974 - val_loss: 9.1025
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4965 - loss: 2.3639 - val_accuracy: 0.0925 - val_loss: 9.1497
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5039 - loss: 2.3290 - val_accuracy: 0.0937 - val_loss: 9.2182
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5089 - loss: 2.2980 - val_accuracy: 0.0947 - val_loss: 9.2675
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5149 - loss: 2.2647 - val_accuracy: 0.0919 - val_loss: 9.3176
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5215 - loss: 2.2345 - val_accuracy: 0.0937 - val_loss: 9.3809
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5274 - loss: 2.2031 - val_accuracy: 0.0944 - val_loss: 9.4366
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5328 - loss: 2.1739 - val_accuracy: 0.0938 - val_loss: 9.4908
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5386 - loss: 2.1457 - val_accuracy: 0.0922 - val_loss: 9.5425
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5441 - loss: 2.1160 - val_accuracy: 0.0936 - val_loss: 9.5963
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5484 - loss: 2.0886 - val_accuracy: 0.0905 - val_loss: 9.6466
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5555 - loss: 2.0618 - val_accuracy: 0.0902 - val_loss: 9.7075
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5600 - loss: 2.0345 - val_accuracy: 0.0910 - val_loss: 9.7529
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5653 - loss: 2.0089 - val_accuracy: 0.0895 - val_loss: 9.8121
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5695 - loss: 1.9838 - val_accuracy: 0.0905 - val_loss: 9.8790
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 55ms/step - accuracy: 0.5742 - loss: 1.9568 - val_accuracy: 0.0886 - val_loss: 9.9321
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5802 - loss: 1.9345 - val_accuracy: 0.0898 - val_loss: 9.9751
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5849 - loss: 1.9104 - val_accuracy: 0.0895 - val_loss: 10.0264
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5899 - loss: 1.8857 - val_accuracy: 0.0871 - val_loss: 10.0799
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5939 - loss: 1.8638 - val_accuracy: 0.0863 - val_loss: 10.1223
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5986 - loss: 1.8417 - val_accuracy: 0.0878 - val_loss: 10.1779
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6027 - loss: 1.8218 - val_accuracy: 0.0861 - val_loss: 10.2266
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6065 - loss: 1.7982 - val_accuracy: 0.0869 - val_loss: 10.2948
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6109 - loss: 1.7778 - val_accuracy: 0.0861 - val_loss: 10.3341
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 55ms/step - accuracy: 0.6155 - loss: 1.7567 - val_accuracy: 0.0857 - val_loss: 10.3943
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6199 - loss: 1.7355 - val_accuracy: 0.0860 - val_loss: 10.4157
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6230 - loss: 1.7179 - val_accuracy: 0.0850 - val_loss: 10.4909
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6290 - loss: 1.6960 - val_accuracy: 0.0843 - val_loss: 10.5340
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5540 - loss: 2.0356 - val_accuracy: 0.0840 - val_loss: 10.4281
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6067 - loss: 1.7922 - val_accuracy: 0.0858 - val_loss: 10.4950
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6192 - loss: 1.7315 - val_accuracy: 0.0856 - val_loss: 10.5451
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6267 - loss: 1.7003 - val_accuracy: 0.0837 - val_loss: 10.5976
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6333 - loss: 1.6745 - val_accuracy: 0.0886 - val_loss: 10.6533
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6380 - loss: 1.6539 - val_accuracy: 0.0861 - val_loss: 10.6783
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6414 - loss: 1.6326 - val_accuracy: 0.0857 - val_loss: 10.7352
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6452 - loss: 1.6137 - val_accuracy: 0.0834 - val_loss: 10.7838
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6494 - loss: 1.5965 - val_accuracy: 0.0870 - val_loss: 10.8283
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6529 - loss: 1.5770 - val_accuracy: 0.0855 - val_loss: 10.8760
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6565 - loss: 1.5599 - val_accuracy: 0.0823 - val_loss: 10.9297
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6625 - loss: 1.5413 - val_accuracy: 0.0842 - val_loss: 10.9665
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6635 - loss: 1.5257 - val_accuracy: 0.0848 - val_loss: 11.0152
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6668 - loss: 1.5105 - val_accuracy: 0.0844 - val_loss: 11.0824
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6711 - loss: 1.4941 - val_accuracy: 0.0867 - val_loss: 11.1007
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6729 - loss: 1.4796 - val_accuracy: 0.0830 - val_loss: 11.1497
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6775 - loss: 1.4625 - val_accuracy: 0.0823 - val_loss: 11.1891
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6814 - loss: 1.4472 - val_accuracy: 0.0851 - val_loss: 11.2481
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6842 - loss: 1.4334 - val_accuracy: 0.0837 - val_loss: 11.3015
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6863 - loss: 1.4202 - val_accuracy: 0.0818 - val_loss: 11.3592
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6906 - loss: 1.4039 - val_accuracy: 0.0835 - val_loss: 11.3953
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6944 - loss: 1.3897 - val_accuracy: 0.0822 - val_loss: 11.4368
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6969 - loss: 1.3750 - val_accuracy: 0.0823 - val_loss: 11.4729
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7006 - loss: 1.3605 - val_accuracy: 0.0818 - val_loss: 11.5324
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7023 - loss: 1.3473 - val_accuracy: 0.0817 - val_loss: 11.5743
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7046 - loss: 1.3355 - val_accuracy: 0.0790 - val_loss: 11.6186

In [37]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [38]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [41]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [44]:
from re import VERBOSE
from IPython.core.displayhook import tokenize
def predictor(model, tokeinizer, text, max_len):
  text = text.lower()
  seq = tokeinizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')
  pred = model.predict(seq, verbose=0)
  pred_word_index = np.argmax(pred)
  return index_to_word[pred_word_index]

In [49]:
seed_text = "life is about"
next_word = predictor(lstm_model, tokeinizer, seed_text, max_len)
print(f"Next Word: {next_word}")

Next Word: accepting

In [55]:
def generate_text(model, tokenizer, seed_text, max_len, num_words):
  for _ in range(num_words):
    next_word = predictor(model, tokenizer, seed_text, max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [56]:
seed = "life is about"
generate_text = generate_text(lstm_model, tokeinizer, seed, max_len, 10)
print(generate_text)

life is about accepting the challenges along the way choosing to keep moving

In [66]:
import pickle
with open('tokenizer.pkl', 'wb') as file:
  pickle.dump(tokeinizer, file)

In [67]:
with open('max_len', 'wb') as file:
  pickle.dump(max_len, file)

In [69]:
# max_len is an integer, so we use pickle to save it (as done in the previous cell)
import pickle
with open('max_len.pkl', 'wb') as file:
    pickle.dump(max_len, file)
print("max_len saved to max_len.pkl")

max_len saved to max_len.pkl